name: Run Tests QA Environment
run-name: Test Execution QA

on: 
 push:
    branches: [ qa ]


jobs:
  environment-setup:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [19.x]
        include:

          - site: "testing"
            datacenter: "site-qa"
    runs-on: ${{ matrix.os }}
    #runs-on: macos-latest #why linux and not macosx.
    #strategy:
      #matrix:
        #node-version: [19.x]


    steps:

      - uses: actions/checkout@v3
      - name: Run Node - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g newman #por las dudas install antes ya que es necesario para CI
      - run: newman run "${{secrets.RUN_COLLECTION}}" --environment "${{secrets.RUN_ENVIRONMENT_QA}}" --reporter-junit-export "newman/test.xml"

      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
         apiKey: ${{secrets.POSTMAN_APIKEY}}
         collection: ${{secrets.RUN_COLLECTION}}
         environment: ${{secrets.RUN_ENVIRONMENT_QA}}
         reporters: '["junit"]'
         reporter: '[ junit: {export : "./xmlResults.xml"}]'
